# Generated by Django 2.2.13 on 2021-03-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Qid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Question.Question'),
        ),
    ]
