# Generated by Django 2.2.13 on 2021-03-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20210307_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='countstar',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='countstar',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
