# Generated by Django 2.2.13 on 2021-03-11 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question', '0004_auto_20210310_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='countstar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='countstar',
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(related_name='ans_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='que_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
