# Generated by Django 2.2.13 on 2021-03-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0009_auto_20210312_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='ans_comment', to='Question.Comment'),
        ),
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='que_comment', to='Question.Comment'),
        ),
    ]
