# Generated by Django 2.2.13 on 2021-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0012_auto_20210312_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ismain',
            field=models.BooleanField(default=False),
        ),
    ]
