# Generated by Django 2.2.13 on 2021-03-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0013_comment_ismain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ismain',
        ),
    ]
