# Generated by Django 2.2.13 on 2021-03-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0014_remove_comment_ismain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='ans_comment', to='Question.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Question.Comment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='que_comment', to='Question.Comment'),
        ),
    ]
