# Generated by Django 2.2.13 on 2021-03-31 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0015_auto_20210312_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='ans_comment', to='Question.Comment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='ans_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='que_comment', to='Question.Comment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='que_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
