# Generated by Django 2.2.13 on 2021-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210307_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ismale',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
